### ISSUE TITLE
Responsive not working

### ISSUE THREAD

**Issue by jhubb-io** [caddis/craft-wistia#22]
I haven't dug into your code too much yet, but the Wistia embed isn't in the correct format to allow responsive to work properly.

Here is the correct code (without ability to input settings etc - hence no PR).

<script src="https://fast.wistia.com/embed/medias/{{ hashedId }}.jsonp" async></script><script src="https://fast.wistia.com/assets/external/E-v1.js" async></script><div class="wistia_responsive_padding" style="padding:56.25% 0 0 0;position:relative;"><div class="wistia_responsive_wrapper" style="height:100%;left:0;position:absolute;top:0;width:100%;"><div class="wistia_embed wistia_async_{{ hashedId }} videoFoam=true" style="height:100%;width:100%">&nbsp;</div></div></div>

**Comment by ryanbrookepayne** [comment]
@jhubb-io Please clarify what you mean by "the Wistia embed isn't in the correct format to allow responsive to work properly"?

Also, I'm not familiar with the "correct code" you are referencing. We're outputting the embed based on what the [Wistia javascript api](https://wistia.com/doc/player-api#get_started) details. An example of that would be:

```
<script src="//fast.wistia.com/assets/external/E-v1.js" async></script>
<div class="wistia_embed wistia_async_[HASHEDID]" style="width:640px;height:360px;"></div>
```

We're also outputting the embed options into the div's class as defined in the [Wistia embed options](https://wistia.com/doc/embed-options#setting_options_on_standard_and_popover_embeds). `videoFoam` (which makes the video responsive) is being applied based on your parameter input.

```
<script src="//fast.wistia.com/assets/external/E-v1.js" async></script>
<div class="wistia_embed wistia_async_[HASHEDID] videoFoam=true playerColor=ff0000"
style="width:640px;height:360px;"></div>
```

Let me know if that helps.

**Comment by ryanbrookepayne** [comment]
@jhubb-io Anymore thoughts on this? If not, I will go ahead and close this issue.

**Comment by jhubb-io** [comment]
Hey, sorry it took a while to respond. I have used your standard embed and the videos are not responsive at all (they break out of their container). I'll do some more testing and get back to you.

**Comment by ryanbrookepayne** [comment]
@jhubb-io ok. What do you mean by "they break out of their container"? A screenshot would be helpful.

**Comment by Am1tBiswas** [comment]
Still not working...

<script src="//fast.wistia.com/assets/external/E-v1.js" async></script>
<div class="wistia_embed wistia_async_asdfdfd" style="height:360px;position:relative;width:640px"></div>
<script>
window._wq = window._wq || [];
_wq.push({ id: 'fasdfadsf', onReady: function(video) {
  console.log("I got a handle to the video!", video);
}});
</script>

**Comment by ryanbrookepayne** [comment]
@Amit-Biswas This plugin has been deprecated and is no longer in active development. You might try https://github.com/lewiscommunications/craft-wistia but I'm not sure that is being actively developed either.
